### ISSUE TITLE
Change parameters on UHS API endpoints to take ids, not names

### ISSUE THREAD

**Issue by richscott** [G-Research/unicorn-history-server#318] opened 2024-11-01 14:59 UTC
Now that the G-Research fork of Yunikorn Scheduler assigns unique IDs to scheduler objects and they are rendered in the event stream and their API, change the UHS API endpoints from taking name-based parameters to taking id-based parameters. The endpoints include:
```
/api/v1/partition/{partition_name}/queues
/api/v1/partition/{partition_name}/queue/{queue_name}/applications
/api/v1/partition/{partition_name}/nodes
```

**Comment by nikola-jokic** [comment] 2024-11-04 14:23
Closing as duplicate of #316

**Closed by nikola-jokic** 2024-11-04 14:23 UTC
